"""empty message

Revision ID: 64540ab51bae
Revises: ffdc0a98111c
Create Date: 2021-04-26 10:38:56.658293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64540ab51bae'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('coinId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('averagePrice', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['coinId'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'coinId', name='own_coin_once')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tradePrice', sa.Float(), nullable=False),
    sa.Column('tradeSize', sa.Float(), nullable=False),
    sa.Column('buyOrSell', sa.String(length=50), nullable=False),
    sa.Column('dateOfTrade', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('coinId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coinId'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('coinId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coinId'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId', 'coinId', name='unique_coin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_table('trades')
    op.drop_table('portfolios')
    op.drop_table('coins')
    # ### end Alembic commands ###
