"""empty message

Revision ID: 8f9dec058a7d
Revises: 9f165a359f6d
Create Date: 2021-04-24 07:14:52.037509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9dec058a7d'
down_revision = '9f165a359f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_coin', 'watchlists', ['userId', 'coinId'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_coin', 'watchlists', type_='unique')
    # ### end Alembic commands ###
