"""empty message

Revision ID: 2d3a408f3919
Revises: db80f59f7efb
Create Date: 2021-06-08 15:14:04.360077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3a408f3919'
down_revision = 'db80f59f7efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('us_dollar', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'us_dollar')
    # ### end Alembic commands ###
