"""empty message

Revision ID: 6cb9c6ea10ac
Revises: 39d884bda6e9
Create Date: 2021-04-25 17:20:50.883986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb9c6ea10ac'
down_revision = '39d884bda6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'watchlists', 'coins', ['coinId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watchlists', type_='foreignkey')
    # ### end Alembic commands ###
