"""empty message

Revision ID: 3697dac7deaa
Revises: 054d3942bfd5
Create Date: 2021-04-25 16:07:29.830657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3697dac7deaa'
down_revision = '054d3942bfd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('averagePrice', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'averagePrice')
    # ### end Alembic commands ###
