"""empty message

Revision ID: 39d884bda6e9
Revises: 3697dac7deaa
Create Date: 2021-04-25 16:20:25.703374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d884bda6e9'
down_revision = '3697dac7deaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tradePrice', sa.Float(), nullable=False),
    sa.Column('tradeSize', sa.Float(), nullable=False),
    sa.Column('buyOrSell', sa.Boolean(), nullable=False),
    sa.Column('dateOfTrade', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('coinId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coinId'], ['coins.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
